function [fitresult, gof] = createFit1(x1, y1)
%CREATEFIT1(X1,Y1)
%  Create a fit.
%
%  Data for 'INA118 Gain fit' fit:
%      X Input : x1
%      Y Output: y1
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 10-Sep-2019 12:21:17


%% Fit: 'INA118 Gain fit'.
[xData, yData] = prepareCurveData( x1, y1 );

% Set up fittype and options.
ft = fittype( 'power1' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [47.4013658412893 -0.808290110076875];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'INA118 Gain fit' );
h = plot( fitresult, xData, yData );
legend( h, 'y1 vs. x1', 'INA118 Gain fit', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'x1', 'Interpreter', 'none' );
ylabel( 'y1', 'Interpreter', 'none' );
grid on


